spring:
  application:
    name: task-api
  
  # JPA and Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # PostgreSQL Database configuration
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:5432}/${SPRING_DATASOURCE_NAME:tdd_db}
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  
  # Server configuration
  web:
    resources:
      add-mappings: false

server:
  port: 8080
  servlet:
    context-path: /api

# Logging configuration
logging:
  level:
    root: INFO
    mentoring.study.tdd: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

